# ===============================
# = GOOGLE
# ===============================
google:
  api:
    key: AIzaSyA0bOrpaALYb-6caX32Da5KASA94zAoSik
    read-timeout: 1500
    write-timeout: 1500
    connect-timeout: 3000
    requests-limit: 10
    venue-limit: 20
    call-fail-delay: 1500

# ===============================
# = FOURSQUARE
# ===============================
foursquare:
  api:
    client-id: PQDUHRGQ3LRAIQBMC5VJZTR0ZENNBYO03Q1ERFXXG1HI0Y1S
    client-secret: 2ARYMHXILVTZXYSLZL5THOPWK1OGGIQW03FFRWYG52OCBMRK
    redirect-url:
    venue-limit: 25 # real 30 but in some cases 4sq return fake count
    call-fail-delay: 1500

# ===============================
# = Venue Source Categories
# = Foursquare: https://developer.foursquare.com/docs/resources/categories
# = Google: https://developers.google.com/places/supported_types
# ===============================
venue:
  lower-rating-bound: 0.05 # <- this part from average rating by category
  categories:
    -
      title: Art
      google-keys:
        - museum
        - art_gallery
      foursquare-keys:
        - 4bf58dd8d48988d181941735 # Museum
        - 4bf58dd8d48988d18f941735 # Art museum
        - 4bf58dd8d48988d190941735 # History museum
        - 4bf58dd8d48988d191941735 # Science museum
        - 4bf58dd8d48988d192941735 # Planetarium
        - 4bf58dd8d48988d137941735 # Theater
        - 4bf58dd8d48988d136941735 # Opera House
        - 4bf58dd8d48988d1e2931735 # Art Gallery
        - 52e81612bcbc57f1066b79ed # Outdoor Sculpture
        - 4bf58dd8d48988d12d941735 # Monument / Landmark
        - 52e81612bcbc57f1066b7a32 # Cultural Center
        - 50aaa49e4b90af0d42d5de11 # Castle
        - 4deefb944765f83613cdba6e # Historic Site
    -
      title: Catering
      google-keys:
        - bakery
        - cafe
        - restaurant
      foursquare-keys:
        - 4bf58dd8d48988d16d941735 # Cafe
        - 4bf58dd8d48988d16a941735 # Bakery
        - 4bf58dd8d48988d1c4941735 # Restaurant
        - 5293a7563cf9994f4e043a44 # Russian Restaurant
        - 4bf58dd8d48988d1c1941735 # Mexican Restaurant
        - 4bf58dd8d48988d110941735 # Italian Restaurant
        - 4bf58dd8d48988d10c941735 # French Restaurant
    -
      title: Municipality
      google-keys:
        - city_hall
        - library
        - local_government_office
        - train_station
      foursquare-keys:
        - 4bf58dd8d48988d12f941735 # Library
        - 52e81612bcbc57f1066b7a38 # Town Hall
        - 4bf58dd8d48988d126941735 # Government Building
        - 4bf58dd8d48988d12a941735 # Capitol Building
        - 4bf58dd8d48988d1df941735 # Bridge
    -
      title: Nature
      google-keys:
        - park
      foursquare-keys:
        - 4bf58dd8d48988d163941735 # Park
        - 4bf58dd8d48988d15a941735 # Garden
        - 52e81612bcbc57f1066b7a23 # Forest
        - 52e81612bcbc57f1066b7a21 # National Park
        - 56aa371be4b08b9a8d573560 # Waterfall
    -
      title: Shrine
      google-keys:
        - church
        - hindu_temple
        - synagogue
        - mosque
      foursquare-keys:
        - 4bf58dd8d48988d132941735 # Church
        - 4bf58dd8d48988d138941735 # Mosque
        - 52e81612bcbc57f1066b7a3e # Buddhist Temple
        - 4bf58dd8d48988d13a941735 # Temple
        - 4eb1d80a4b900d56c88a45ff # Shrine
        - 4bf58dd8d48988d139941735 # Synagogue
        - 52e81612bcbc57f1066b7a40 # Monastery


# ===============================
# = POSTGRESQL / JPA / HIBERNATE
# ===============================
spring:
  datasource:
    platform: postgres
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/heat-map-trip
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 10000
#      idle-timeout: 10000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update # (create, create-drop, update) schema will be automatically updated afresh for every start of application
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
