# ===============================
# = GOOGLE
# ===============================
google:
  api:
    key: AIzaSyA0bOrpaALYb-6caX32Da5KASA94zAoSik
    read-timeout: 1500
    write-timeout: 1500
    connect-timeout: 3000
    requests-limit: 10
    venue-limit: 20
    call-fail-delay: 1500

# ===============================
# = Venue Source Categories
# ===============================
venue:
  category:
    google:
      park: park

